version: 2

defaults: &defaults
  docker:
    - image: circleci/openjdk:8-jdk
  working_directory: ~/repo
  environment:
    TERM: xterm
    DEBIAN_FRONTEND: noninteractive
    DISABLE_SCALAFMT: true
    JVM_OPTS: -Xmx3200m

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: sbt ^test:compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: sbt ^test
  release:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - add_ssh_keys:
          fingerprints:
            - "bf:24:38:ce:25:6b:8c:da:e6:3a:b4:e7:23:66:b6:59"
      - run:
          name: Set up git
          command: |
            git config --global user.name "CircleCI"
            git config --global user.email "mwz@users.noreply.github.com"
            ssh-keyscan -T 15 github.com >> ~/.ssh/known_hosts
      - run: sbt 'release with-defaults skip-tests' < /dev/null

workflows:
  version: 2
  sbt-sonar:
    jobs:
      - test
      - hold:
          type: approval
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - hold
          filters:
            branches:
              only: master
